Update scripts on bin/ description

diff --git a/bin/compract b/bin/compract
--- a/bin/compract
+++ b/bin/compract
@@ -1,21 +1,44 @@
-#!/bin/sh
+#!/bin/bash
 
-### compract - compress / extract files
+## compract - compress / extract files
+echo "Sorry. This Command hadn't been implemented yet." && exit 1
 
-usage() {
+compract::usage() {
   name=`basename $0`
   cat <<EOF
 Usage:
-  compract -ce Command path targets...
-Options:
-  -c    Compress files.
-  -e    Extract files.
-Commands:
-  zip   Compress / Extract to .zip
-  gz    Compress / Extract to .tar.gz
-  bz    Compress / Extract to .tar.bz2
+  compract OPTION [COMPRESS COMMAND] targets...
+OPTIONS:
+  -c    Compress files
+  -e    Extract files
+  -h    Display usage
+COMPRESS COMMANDS:
+  zip   To .zip file
+  gz    To .tar.gz file
+  bz    To .tar.bz2 file
 EOF
+}
+
+error() {
+  echo $1 1>&2
   exit 1
 }
 
+# compract::compress() {
+# }
+#
+# compract::extract() {
+# }
 
+main() {
+  [ $# -eq 0 ] && error "TODO: Error"
+
+  case "$1" in
+    -c) compract::compress $@ ;;
+    -e) compract::extract $@ ;;
+    -h) compract::usage ;;
+    *)  error
+  esac
+}
+
+main $@
